[package]
name = "sui-axelar-cgp"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", rev = "20cf9113de06eb728cd57decdecc836813988767", subdir = "crates/sui-framework/packages/sui-framework"}

[addresses]
axelar = "0x0"
sui = "0x2"
